# Form implementation generated from reading ui file 'graficos.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.stackedWidget.sizePolicy().hasHeightForWidth()
        )
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.menu = QtWidgets.QWidget()
        self.menu.setEnabled(True)
        self.menu.setObjectName("menu")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.menu)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Castorplot = QtWidgets.QLabel(self.menu)
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.Castorplot.setFont(font)
        self.Castorplot.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Castorplot.setObjectName("Castorplot")
        self.gridLayout_9.addWidget(self.Castorplot, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_9.addItem(spacerItem, 1, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.menu)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Importar_dados = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Importar_dados.sizePolicy().hasHeightForWidth()
        )
        self.Importar_dados.setSizePolicy(sizePolicy)
        self.Importar_dados.setMinimumSize(QtCore.QSize(300, 100))
        self.Importar_dados.setMaximumSize(QtCore.QSize(100000, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Importar_dados.setFont(font)
        self.Importar_dados.setObjectName("Importar_dados")
        self.gridLayout_2.addWidget(self.Importar_dados, 0, 1, 1, 1)
        self.Sobre = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sobre.sizePolicy().hasHeightForWidth())
        self.Sobre.setSizePolicy(sizePolicy)
        self.Sobre.setMinimumSize(QtCore.QSize(300, 100))
        self.Sobre.setMaximumSize(QtCore.QSize(100000, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Sobre.setFont(font)
        self.Sobre.setObjectName("Sobre")
        self.gridLayout_2.addWidget(self.Sobre, 1, 2, 1, 1)
        self.Ajuda = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ajuda.sizePolicy().hasHeightForWidth())
        self.Ajuda.setSizePolicy(sizePolicy)
        self.Ajuda.setMinimumSize(QtCore.QSize(300, 100))
        self.Ajuda.setMaximumSize(QtCore.QSize(100000, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Ajuda.setFont(font)
        self.Ajuda.setObjectName("Ajuda")
        self.gridLayout_2.addWidget(self.Ajuda, 1, 1, 1, 1)
        self.Arquivo_abrir = QtWidgets.QPushButton(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Arquivo_abrir.sizePolicy().hasHeightForWidth()
        )
        self.Arquivo_abrir.setSizePolicy(sizePolicy)
        self.Arquivo_abrir.setMinimumSize(QtCore.QSize(300, 100))
        self.Arquivo_abrir.setMaximumSize(QtCore.QSize(100000, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Arquivo_abrir.setFont(font)
        self.Arquivo_abrir.setObjectName("Arquivo_abrir")
        self.gridLayout_2.addWidget(self.Arquivo_abrir, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.widget_8, 2, 0, 2, 1)
        self.stackedWidget.addWidget(self.menu)
        self.importar = QtWidgets.QWidget()
        self.importar.setObjectName("importar")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.importar)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.importar)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.continuar_import = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.continuar_import.setFont(font)
        self.continuar_import.setObjectName("continuar_import")
        self.gridLayout_5.addWidget(self.continuar_import, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        self.voltar_import = QtWidgets.QPushButton(self.widget_3)
        self.voltar_import.setObjectName("voltar_import")
        self.gridLayout_5.addWidget(self.voltar_import, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.importar)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.cabealho_ignorar_3 = QtWidgets.QSpinBox(self.importar)
        self.cabealho_ignorar_3.setObjectName("cabealho_ignorar_3")
        self.verticalLayout_3.addWidget(self.cabealho_ignorar_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.line_5 = QtWidgets.QFrame(self.importar)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_4.addWidget(self.line_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.importar)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.delimitador_3 = QtWidgets.QLineEdit(self.importar)
        self.delimitador_3.setObjectName("delimitador_3")
        self.verticalLayout_4.addWidget(self.delimitador_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.line_6 = QtWidgets.QFrame(self.importar)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_4.addWidget(self.line_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.importar)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.separador_decimal_3 = QtWidgets.QLineEdit(self.importar)
        self.separador_decimal_3.setObjectName("separador_decimal_3")
        self.verticalLayout_5.addWidget(self.separador_decimal_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.importar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Caminho_arquivo = QtWidgets.QLabel(self.importar)
        self.Caminho_arquivo.setObjectName("Caminho_arquivo")
        self.horizontalLayout_3.addWidget(self.Caminho_arquivo)
        self.procurar_arquivo = QtWidgets.QPushButton(self.importar)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.procurar_arquivo.setFont(font)
        self.procurar_arquivo.setObjectName("procurar_arquivo")
        self.horizontalLayout_3.addWidget(self.procurar_arquivo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.importar)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 977, 502))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.addWidget(self.scrollArea_3, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.importar)
        self.plot_puro = QtWidgets.QWidget()
        self.plot_puro.setObjectName("plot_puro")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.plot_puro)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_15 = QtWidgets.QLabel(self.plot_puro)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.plot_puro)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_7.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.plot_puro)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.continuar_dados_puros = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.continuar_dados_puros.setFont(font)
        self.continuar_dados_puros.setObjectName("continuar_dados_puros")
        self.gridLayout_6.addWidget(self.continuar_dados_puros, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        self.voltar_dados_puros = QtWidgets.QPushButton(self.widget_4)
        self.voltar_dados_puros.setObjectName("voltar_dados_puros")
        self.gridLayout_6.addWidget(self.voltar_dados_puros, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_4, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.plot_puro)
        self.analise = QtWidgets.QWidget()
        self.analise.setObjectName("analise")
        self.gridLayout = QtWidgets.QGridLayout(self.analise)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.analise)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout.addWidget(self.graphicsView_2, 3, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.analise)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.analise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.analise)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.voltar_analise = QtWidgets.QPushButton(self.widget_6)
        self.voltar_analise.setObjectName("voltar_analise")
        self.gridLayout_8.addWidget(self.voltar_analise, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_8.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_6, 4, 0, 1, 4)
        self.tabWidget = QtWidgets.QTabWidget(self.analise)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 10000))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollArea.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored
        )
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 349, 753))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_68 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.widget_15 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.check_nverter_eixo = QtWidgets.QCheckBox(self.widget_15)
        self.check_nverter_eixo.setObjectName("check_nverter_eixo")
        self.gridLayout_15.addWidget(self.check_nverter_eixo, 4, 0, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.widget_15)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_18.addWidget(self.label_17)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Slide_distancia_linha = QtWidgets.QSlider(self.widget_15)
        self.Slide_distancia_linha.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slide_distancia_linha.setObjectName("Slide_distancia_linha")
        self.horizontalLayout_12.addWidget(self.Slide_distancia_linha)
        self.Spin_distancia_linhas = QtWidgets.QDoubleSpinBox(self.widget_15)
        self.Spin_distancia_linhas.setObjectName("Spin_distancia_linhas")
        self.horizontalLayout_12.addWidget(self.Spin_distancia_linhas)
        self.verticalLayout_18.addLayout(self.horizontalLayout_12)
        self.gridLayout_15.addLayout(self.verticalLayout_18, 0, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_15)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_15)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Slider_minimox = QtWidgets.QSlider(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Slider_minimox.sizePolicy().hasHeightForWidth()
        )
        self.Slider_minimox.setSizePolicy(sizePolicy)
        self.Slider_minimox.setMinimumSize(QtCore.QSize(100, 0))
        self.Slider_minimox.setTabletTracking(False)
        self.Slider_minimox.setAcceptDrops(False)
        self.Slider_minimox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider_minimox.setObjectName("Slider_minimox")
        self.horizontalLayout_7.addWidget(self.Slider_minimox)
        self.Spin_minimox = QtWidgets.QDoubleSpinBox(self.widget_15)
        self.Spin_minimox.setObjectName("Spin_minimox")
        self.horizontalLayout_7.addWidget(self.Spin_minimox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_13.addLayout(self.verticalLayout_6)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.widget_15)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Slider_maximox = QtWidgets.QSlider(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Slider_maximox.sizePolicy().hasHeightForWidth()
        )
        self.Slider_maximox.setSizePolicy(sizePolicy)
        self.Slider_maximox.setMinimumSize(QtCore.QSize(100, 0))
        self.Slider_maximox.setTabletTracking(False)
        self.Slider_maximox.setAcceptDrops(False)
        self.Slider_maximox.setMaximum(100)
        self.Slider_maximox.setProperty("value", 100)
        self.Slider_maximox.setSliderPosition(100)
        self.Slider_maximox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider_maximox.setObjectName("Slider_maximox")
        self.horizontalLayout_9.addWidget(self.Slider_maximox)
        self.Spin_maximox = QtWidgets.QDoubleSpinBox(self.widget_15)
        self.Spin_maximox.setObjectName("Spin_maximox")
        self.horizontalLayout_9.addWidget(self.Spin_maximox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_13.addLayout(self.verticalLayout_10)
        self.gridLayout_15.addLayout(self.verticalLayout_13, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_15.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_15.addItem(spacerItem5, 3, 0, 1, 1)
        self.verticalLayout_68.addWidget(self.widget_15)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_68.addWidget(self.label_44)
        self.widget_14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_8 = QtWidgets.QLabel(self.widget_14)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_16.addWidget(self.label_8)
        self.label_14 = QtWidgets.QLabel(self.widget_14)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_16.addWidget(self.label_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Slider_minimox_norm = QtWidgets.QSlider(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Slider_minimox_norm.sizePolicy().hasHeightForWidth()
        )
        self.Slider_minimox_norm.setSizePolicy(sizePolicy)
        self.Slider_minimox_norm.setMinimumSize(QtCore.QSize(100, 0))
        self.Slider_minimox_norm.setTabletTracking(False)
        self.Slider_minimox_norm.setAcceptDrops(False)
        self.Slider_minimox_norm.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider_minimox_norm.setObjectName("Slider_minimox_norm")
        self.horizontalLayout_13.addWidget(self.Slider_minimox_norm)
        self.Spin_minimox_norm = QtWidgets.QDoubleSpinBox(self.widget_14)
        self.Spin_minimox_norm.setObjectName("Spin_minimox_norm")
        self.horizontalLayout_13.addWidget(self.Spin_minimox_norm)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.widget_14)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Slider_maximox_norm = QtWidgets.QSlider(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Slider_maximox_norm.sizePolicy().hasHeightForWidth()
        )
        self.Slider_maximox_norm.setSizePolicy(sizePolicy)
        self.Slider_maximox_norm.setMinimumSize(QtCore.QSize(100, 0))
        self.Slider_maximox_norm.setTabletTracking(False)
        self.Slider_maximox_norm.setAcceptDrops(False)
        self.Slider_maximox_norm.setMaximum(100)
        self.Slider_maximox_norm.setSliderPosition(100)
        self.Slider_maximox_norm.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider_maximox_norm.setObjectName("Slider_maximox_norm")
        self.horizontalLayout_14.addWidget(self.Slider_maximox_norm)
        self.Spin_maximox_norm = QtWidgets.QDoubleSpinBox(self.widget_14)
        self.Spin_maximox_norm.setObjectName("Spin_maximox_norm")
        self.horizontalLayout_14.addWidget(self.Spin_maximox_norm)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.verticalLayout_15.addLayout(self.verticalLayout_17)
        self.verticalLayout_26.addLayout(self.verticalLayout_15)
        self.check_normalizar_dados = QtWidgets.QCheckBox(self.widget_14)
        self.check_normalizar_dados.setObjectName("check_normalizar_dados")
        self.verticalLayout_26.addWidget(self.check_normalizar_dados)
        self.verticalLayout_68.addWidget(self.widget_14)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_68.addWidget(self.label_43)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.Avancado = QtWidgets.QCheckBox(self.widget)
        self.Avancado.setObjectName("Avancado")
        self.verticalLayout_24.addWidget(self.Avancado)
        spacerItem6 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_24.addItem(spacerItem6)
        self.gridLayout_16.addLayout(self.verticalLayout_24, 0, 0, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.widget)
        self.widget_16.setEnabled(False)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Modpoly = QtWidgets.QRadioButton(self.widget_16)
        self.Modpoly.setObjectName("Modpoly")
        self.verticalLayout_19.addWidget(self.Modpoly)
        self.ImodPloy = QtWidgets.QRadioButton(self.widget_16)
        self.ImodPloy.setObjectName("ImodPloy")
        self.verticalLayout_19.addWidget(self.ImodPloy)
        self.Zhangfit = QtWidgets.QRadioButton(self.widget_16)
        self.Zhangfit.setObjectName("Zhangfit")
        self.verticalLayout_19.addWidget(self.Zhangfit)
        self.horizontalLayout.addLayout(self.verticalLayout_19)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_45 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_20.addWidget(self.label_45)
        self.label_20 = QtWidgets.QLabel(self.widget_16)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_20.addWidget(self.label_20)
        self.baseline_parametro_1 = QtWidgets.QDoubleSpinBox(self.widget_16)
        self.baseline_parametro_1.setMaximum(100.0)
        self.baseline_parametro_1.setProperty("value", 100.0)
        self.baseline_parametro_1.setObjectName("baseline_parametro_1")
        self.verticalLayout_20.addWidget(self.baseline_parametro_1)
        self.verticalLayout_23.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_19 = QtWidgets.QLabel(self.widget_16)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_21.addWidget(self.label_19)
        self.baseline_parametro_2 = QtWidgets.QDoubleSpinBox(self.widget_16)
        self.baseline_parametro_2.setProperty("value", 1.0)
        self.baseline_parametro_2.setObjectName("baseline_parametro_2")
        self.verticalLayout_21.addWidget(self.baseline_parametro_2)
        self.verticalLayout_23.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_18 = QtWidgets.QLabel(self.widget_16)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_22.addWidget(self.label_18)
        self.baseline_parametro_3 = QtWidgets.QDoubleSpinBox(self.widget_16)
        self.baseline_parametro_3.setProperty("value", 15.0)
        self.baseline_parametro_3.setObjectName("baseline_parametro_3")
        self.verticalLayout_22.addWidget(self.baseline_parametro_3)
        self.verticalLayout_23.addLayout(self.verticalLayout_22)
        self.horizontalLayout.addLayout(self.verticalLayout_23)
        self.gridLayout_16.addWidget(self.widget_16, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_16.addWidget(self.checkBox, 1, 0, 1, 1)
        self.verticalLayout_68.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_28.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_9)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 349, 738))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_46 = QtWidgets.QLabel(self.widget_9)
        self.label_46.setObjectName("label_46")
        self.verticalLayout.addWidget(self.label_46)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_47 = QtWidgets.QLabel(self.widget_9)
        self.label_47.setObjectName("label_47")
        self.verticalLayout.addWidget(self.label_47)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.label_48 = QtWidgets.QLabel(self.widget_9)
        self.label_48.setObjectName("label_48")
        self.verticalLayout.addWidget(self.label_48)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.verticalLayout_14.addWidget(self.widget_9)
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_7 = QtWidgets.QLabel(self.widget_12)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_30.addWidget(self.label_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_24 = QtWidgets.QLabel(self.widget_12)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.Cor_texto = QtWidgets.QLineEdit(self.widget_12)
        self.Cor_texto.setObjectName("Cor_texto")
        self.horizontalLayout_11.addWidget(self.Cor_texto)
        self.cor_picker_texto = QtWidgets.QPushButton(self.widget_12)
        self.cor_picker_texto.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("img/color.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.cor_picker_texto.setIcon(icon)
        self.cor_picker_texto.setCheckable(False)
        self.cor_picker_texto.setAutoRepeat(False)
        self.cor_picker_texto.setAutoExclusive(False)
        self.cor_picker_texto.setAutoDefault(False)
        self.cor_picker_texto.setObjectName("cor_picker_texto")
        self.horizontalLayout_11.addWidget(self.cor_picker_texto)
        self.verticalLayout_30.addLayout(self.horizontalLayout_11)
        self.verticalLayout_14.addWidget(self.widget_12)
        self.widget_22 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_42 = QtWidgets.QLabel(self.widget_22)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_42.addWidget(self.label_42)
        self.comboBox = QtWidgets.QComboBox(self.widget_22)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_42.addWidget(self.comboBox)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_52 = QtWidgets.QLabel(self.widget_22)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_25.addWidget(self.label_52)
        self.Cor_linha = QtWidgets.QLineEdit(self.widget_22)
        self.Cor_linha.setText("")
        self.Cor_linha.setObjectName("Cor_linha")
        self.horizontalLayout_25.addWidget(self.Cor_linha)
        self.cor_picker_linha = QtWidgets.QPushButton(self.widget_22)
        self.cor_picker_linha.setText("")
        self.cor_picker_linha.setIcon(icon)
        self.cor_picker_linha.setCheckable(False)
        self.cor_picker_linha.setAutoRepeat(False)
        self.cor_picker_linha.setAutoExclusive(False)
        self.cor_picker_linha.setAutoDefault(False)
        self.cor_picker_linha.setObjectName("cor_picker_linha")
        self.horizontalLayout_25.addWidget(self.cor_picker_linha)
        self.verticalLayout_42.addLayout(self.horizontalLayout_25)
        self.verticalLayout_14.addWidget(self.widget_22)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_5 = QtWidgets.QLabel(self.widget_10)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_27.addWidget(self.label_5)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_10)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_27.addWidget(self.checkBox_2)
        self.widget_23 = QtWidgets.QWidget(self.widget_10)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.widget_23)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.Cor_borda = QtWidgets.QLineEdit(self.widget_23)
        self.Cor_borda.setObjectName("Cor_borda")
        self.horizontalLayout_8.addWidget(self.Cor_borda)
        self.cor_picker_borda = QtWidgets.QPushButton(self.widget_23)
        self.cor_picker_borda.setText("")
        self.cor_picker_borda.setIcon(icon)
        self.cor_picker_borda.setCheckable(False)
        self.cor_picker_borda.setAutoRepeat(False)
        self.cor_picker_borda.setAutoExclusive(False)
        self.cor_picker_borda.setAutoDefault(False)
        self.cor_picker_borda.setObjectName("cor_picker_borda")
        self.horizontalLayout_8.addWidget(self.cor_picker_borda)
        self.verticalLayout_27.addWidget(self.widget_23)
        self.verticalLayout_14.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_6 = QtWidgets.QLabel(self.widget_11)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_29.addWidget(self.label_6)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_11)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_29.addWidget(self.checkBox_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_23 = QtWidgets.QLabel(self.widget_11)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_10.addWidget(self.label_23)
        self.Cor_fundo = QtWidgets.QLineEdit(self.widget_11)
        self.Cor_fundo.setObjectName("Cor_fundo")
        self.horizontalLayout_10.addWidget(self.Cor_fundo)
        self.cor_picker_fundo = QtWidgets.QPushButton(self.widget_11)
        self.cor_picker_fundo.setText("")
        self.cor_picker_fundo.setIcon(icon)
        self.cor_picker_fundo.setCheckable(False)
        self.cor_picker_fundo.setAutoRepeat(False)
        self.cor_picker_fundo.setAutoExclusive(False)
        self.cor_picker_fundo.setAutoDefault(False)
        self.cor_picker_fundo.setObjectName("cor_picker_fundo")
        self.horizontalLayout_10.addWidget(self.cor_picker_fundo)
        self.verticalLayout_29.addLayout(self.horizontalLayout_10)
        self.verticalLayout_14.addWidget(self.widget_11)
        self.widget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_26 = QtWidgets.QLabel(self.widget_13)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_32.addWidget(self.label_26)
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget_13)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_32.addWidget(self.checkBox_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_27 = QtWidgets.QLabel(self.widget_13)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_16.addWidget(self.label_27)
        self.Cor_grade = QtWidgets.QLineEdit(self.widget_13)
        self.Cor_grade.setObjectName("Cor_grade")
        self.horizontalLayout_16.addWidget(self.Cor_grade)
        self.cor_picker_grade = QtWidgets.QPushButton(self.widget_13)
        self.cor_picker_grade.setText("")
        self.cor_picker_grade.setIcon(icon)
        self.cor_picker_grade.setCheckable(False)
        self.cor_picker_grade.setAutoRepeat(False)
        self.cor_picker_grade.setAutoExclusive(False)
        self.cor_picker_grade.setAutoDefault(False)
        self.cor_picker_grade.setObjectName("cor_picker_grade")
        self.horizontalLayout_16.addWidget(self.cor_picker_grade)
        self.verticalLayout_32.addLayout(self.horizontalLayout_16)
        self.verticalLayout_14.addWidget(self.widget_13)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_17.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.widget_7 = QtWidgets.QWidget(self.tab_8)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Exportar_grafico = QtWidgets.QPushButton(self.widget_7)
        self.Exportar_grafico.setObjectName("Exportar_grafico")
        self.verticalLayout_11.addWidget(self.Exportar_grafico)
        self.formato_png = QtWidgets.QRadioButton(self.widget_7)
        self.formato_png.setChecked(True)
        self.formato_png.setObjectName("formato_png")
        self.verticalLayout_11.addWidget(self.formato_png)
        self.formato_pdf = QtWidgets.QRadioButton(self.widget_7)
        self.formato_pdf.setObjectName("formato_pdf")
        self.verticalLayout_11.addWidget(self.formato_pdf)
        self.formato_svg = QtWidgets.QRadioButton(self.widget_7)
        self.formato_svg.setObjectName("formato_svg")
        self.verticalLayout_11.addWidget(self.formato_svg)
        self.verticalLayout_25.addWidget(self.widget_7)
        spacerItem7 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_25.addItem(spacerItem7)
        self.widget_5 = QtWidgets.QWidget(self.tab_8)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Exportar_dados = QtWidgets.QPushButton(self.widget_5)
        self.Exportar_dados.setObjectName("Exportar_dados")
        self.verticalLayout_12.addWidget(self.Exportar_dados)
        self.CSV_export = QtWidgets.QRadioButton(self.widget_5)
        self.CSV_export.setChecked(True)
        self.CSV_export.setObjectName("CSV_export")
        self.verticalLayout_12.addWidget(self.CSV_export)
        self.TXT_export = QtWidgets.QRadioButton(self.widget_5)
        self.TXT_export.setObjectName("TXT_export")
        self.verticalLayout_12.addWidget(self.TXT_export)
        self.verticalLayout_25.addWidget(self.widget_5)
        spacerItem8 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_25.addItem(spacerItem8)
        self.Exportar_analise = QtWidgets.QPushButton(self.tab_8)
        self.Exportar_analise.setObjectName("Exportar_analise")
        self.verticalLayout_25.addWidget(self.Exportar_analise)
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 2, 1)
        self.stackedWidget.addWidget(self.analise)
        self.sobre = QtWidgets.QWidget()
        self.sobre.setObjectName("sobre")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.sobre)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem9 = QtWidgets.QSpacerItem(
            242,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem9, 9, 6, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(
            243,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem10, 9, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.sobre)
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("img/GitHub_40.png"))
        self.label_35.setObjectName("label_35")
        self.gridLayout_10.addWidget(self.label_35, 7, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.sobre)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_10.addWidget(self.line_3, 6, 2, 1, 4)
        self.label_33 = QtWidgets.QLabel(self.sobre)
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("img/GitHub_40.png"))
        self.label_33.setObjectName("label_33")
        self.gridLayout_10.addWidget(self.label_33, 5, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.sobre)
        self.label_36.setOpenExternalLinks(True)
        self.label_36.setObjectName("label_36")
        self.gridLayout_10.addWidget(self.label_36, 7, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.sobre)
        self.label_34.setOpenExternalLinks(True)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 5, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.sobre)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_10.addWidget(self.line_4, 8, 2, 1, 4)
        spacerItem11 = QtWidgets.QSpacerItem(
            243,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem11, 7, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(
            242,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem12, 7, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(
            242,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem13, 5, 6, 1, 1)
        self.widget_17 = QtWidgets.QWidget(self.sobre)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.voltar_sobre = QtWidgets.QPushButton(self.widget_17)
        self.voltar_sobre.setObjectName("voltar_sobre")
        self.horizontalLayout_22.addWidget(self.voltar_sobre)
        spacerItem14 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_22.addItem(spacerItem14)
        self.gridLayout_10.addWidget(self.widget_17, 11, 0, 1, 8)
        self.Castorplot_2 = QtWidgets.QLabel(self.sobre)
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.Castorplot_2.setFont(font)
        self.Castorplot_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Castorplot_2.setObjectName("Castorplot_2")
        self.gridLayout_10.addWidget(self.Castorplot_2, 0, 1, 1, 6)
        self.textBrowser = QtWidgets.QTextBrowser(self.sobre)
        self.textBrowser.setMinimumSize(QtCore.QSize(700, 0))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n" "")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_10.addWidget(self.textBrowser, 1, 1, 1, 6)
        self.line_2 = QtWidgets.QFrame(self.sobre)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_10.addWidget(self.line_2, 4, 2, 1, 4)
        spacerItem15 = QtWidgets.QSpacerItem(
            243,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem15, 3, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem16, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem17, 1, 7, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.sobre)
        self.label_28.setOpenExternalLinks(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 3, 4, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.sobre)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("img/email.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 2, 4, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.sobre)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("img/email_40.png"))
        self.label_25.setObjectName("label_25")
        self.gridLayout_10.addWidget(self.label_25, 3, 2, 1, 2)
        spacerItem18 = QtWidgets.QSpacerItem(
            242,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem18, 3, 6, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(
            243,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout_10.addItem(spacerItem19, 5, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.sobre)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_10.addWidget(self.line_7, 10, 2, 1, 4)
        self.label_37 = QtWidgets.QLabel(self.sobre)
        self.label_37.setOpenExternalLinks(True)
        self.label_37.setObjectName("label_37")
        self.gridLayout_10.addWidget(self.label_37, 9, 4, 1, 1)
        self.stackedWidget.addWidget(self.sobre)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 26))
        self.menubar.setObjectName("menubar")
        self.menuarquivo = QtWidgets.QMenu(self.menubar)
        self.menuarquivo.setObjectName("menuarquivo")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImportar = QtGui.QAction(MainWindow)
        self.actionImportar.setObjectName("actionImportar")
        self.actionManual = QtGui.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.action_novo = QtGui.QAction(MainWindow)
        self.action_novo.setObjectName("action_novo")
        self.actionGitHub = QtGui.QAction(MainWindow)
        self.actionGitHub.setObjectName("actionGitHub")
        self.menuarquivo.addAction(self.action_novo)
        self.menuarquivo.addAction(self.actionImportar)
        self.menuAjuda.addAction(self.actionManual)
        self.menuAjuda.addAction(self.actionGitHub)
        self.menubar.addAction(self.menuarquivo.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # botões interface gráfica
        self.Importar_dados.clicked.connect(
            self.tela_importar
        )  # Botão de importar arquivo
        self.continuar_import.clicked.connect(
            self.continuar_importar
        )  # Botão de continuar na tela de importar
        self.voltar_import.clicked.connect(
            self.voltar_importar
        )  # Botão de voltar na tela de importar
        self.continuar_dados_puros.clicked.connect(
            self.continuar_plot_puro
        )  # Botão de continuar na tela de plot puro
        self.voltar_dados_puros.clicked.connect(
            self.voltar_plot_puro
        )  # Botão de voltar na tela de plot dadps puros
        self.voltar_analise.clicked.connect(
            self.voltar_analise_func
        )  # Botão de voltar na tela de analise
        self.Sobre.clicked.connect(self.tela_sobre)  # Botão de sobre
        self.voltar_sobre.clicked.connect(
            self.voltar_sobre_func
        )  # Botão de voltar na tela sobre

        # Definir caracteres maximos
        self.Cor_borda.setMaxLength(7)
        self.Cor_linha.setMaxLength(7)
        self.Cor_grade.setMaxLength(7)
        self.Cor_fundo.setMaxLength(7)
        self.Cor_texto.setMaxLength(7)

        # cor botões
        self.cor_picker_texto.clicked.connect(self.cor_texto_func)
        self.cor_picker_linha.clicked.connect(self.cor_linha_func)
        self.cor_picker_borda.clicked.connect(self.cor_borda_func)
        self.cor_picker_fundo.clicked.connect(self.cor_fundo_func)
        self.cor_picker_grade.clicked.connect(self.cor_grade_func)

        # mudar cor escrito
        self.Cor_grade.textChanged.connect(self.mudar_cor_escrito_grade)
        self.Cor_fundo.textChanged.connect(self.mudar_cor_escrito_fundo)
        self.Cor_linha.textChanged.connect(self.mudar_cor_escrito_linha)
        self.Cor_texto.textChanged.connect(self.mudar_cor_escrito_texto)
        self.Cor_borda.textChanged.connect(self.mudar_cor_escrito_borda)
        
        #procurar arquivo
        arquivos = self.procurar_arquivo.clicked.connect(self.arquivo_procurar)

    # funções botões GUI
    def tela_importar(self):
        self.stackedWidget.setCurrentIndex(1)

    def continuar_importar(self):
        self.stackedWidget.setCurrentIndex(2)

    def voltar_importar(self):
        self.stackedWidget.setCurrentIndex(0)

    def continuar_plot_puro(self):
        self.stackedWidget.setCurrentIndex(3)

    def voltar_plot_puro(self):
        self.stackedWidget.setCurrentIndex(1)

    def voltar_analise_func(self):
        self.stackedWidget.setCurrentIndex(2)

    def tela_sobre(self):
        self.stackedWidget.setCurrentIndex(4)

    def voltar_sobre_func(self):
        self.stackedWidget.setCurrentIndex(0)

    # funções cor
    def cor_texto_func(self):
        color = QtWidgets.QColorDialog.getColor()
        self.Cor_texto.setText(color.name())
        if color.lightness() > 150:
            self.Cor_texto.setStyleSheet(
                f"""color: #000000;background-color: {color.name()}"""
            )
        else:
            self.Cor_texto.setStyleSheet(
                f"""color: #ffffff;background-color: {color.name()}"""
            )

    def cor_linha_func(self):
        color = QtWidgets.QColorDialog.getColor()
        self.Cor_linha.setText(color.name())
        if color.lightness() > 150:
            self.Cor_linha.setStyleSheet(
                f"""color: #000000;background-color: {color.name()}"""
            )
        else:
            self.Cor_linha.setStyleSheet(
                f"""color: #ffffff;background-color: {color.name()}"""
            )

    def cor_borda_func(self):
        color = QtWidgets.QColorDialog.getColor()
        self.Cor_borda.setText(color.name())
        if color.lightness() > 150:
            self.Cor_borda.setStyleSheet(
                f"""color: #000000;background-color: {color.name()}"""
            )
        else:
            self.Cor_borda.setStyleSheet(
                f"""color: #ffffff;background-color: {color.name()}"""
            )

    def cor_fundo_func(self):
        color = QtWidgets.QColorDialog.getColor()
        self.Cor_fundo.setText(color.name())
        if color.lightness() > 150:
            self.Cor_fundo.setStyleSheet(
                f"""color: #000000;background-color: {color.name()}"""
            )
        else:
            self.Cor_fundo.setStyleSheet(
                f"""color: #ffffff;background-color: {color.name()}"""
            )

    def cor_grade_func(self):
        color = QtWidgets.QColorDialog.getColor()
        self.Cor_grade.setText(color.name())
        if color.lightness() > 150:
            self.Cor_grade.setStyleSheet(
                f"""color: #000000;background-color: {color.name()}"""
            )
        else:
            self.Cor_grade.setStyleSheet(
                f"""color: #ffffff;background-color: {color.name()}"""
            )

    def mudar_cor_escrito_grade(self):
        color_text = self.Cor_grade.text()
        color = QtGui.QColor.fromString(color_text)
        if len(color_text) == 7 and color.isValid():
            if color.lightness() > 150:
                self.Cor_grade.setStyleSheet(
                    f"""color: #000000;background-color: {color_text}"""
                )
            else:
                self.Cor_grade.setStyleSheet(
                    f"""color: #ffffff;background-color: {color_text}"""
                )

    def mudar_cor_escrito_fundo(self):
        color_text = self.Cor_fundo.text()
        color = QtGui.QColor.fromString(color_text)
        if len(color_text) == 7 and color.isValid():
            if color.lightness() > 150:
                self.Cor_fundo.setStyleSheet(
                    f"""color: #000000;background-color: {color_text}"""
                )
            else:
                self.Cor_fundo.setStyleSheet(
                    f"""color: #ffffff;background-color: {color_text}"""
                )

    def mudar_cor_escrito_borda(self):
        color_text = self.Cor_borda.text()
        color = QtGui.QColor.fromString(color_text)
        if len(color_text) == 7 and color.isValid():

            if color.lightness() > 150:
                self.Cor_borda.setStyleSheet(
                    f"""color: #000000;background-color: {color_text}"""
                )
            else:
                self.Cor_borda.setStyleSheet(
                    f"""color: #ffffff;background-color: {color_text}"""
                )

    def mudar_cor_escrito_texto(self):
        color_text = self.Cor_texto.text()
        color = QtGui.QColor.fromString(color_text)
        if len(color_text) == 7 and color.isValid():

            if color.lightness() > 150:
                self.Cor_texto.setStyleSheet(
                    f"""color: #000000;background-color: {color_text}"""
                )
            else:
                self.Cor_texto.setStyleSheet(
                    f"""color: #ffffff;background-color: {color_text}"""
                )

    def mudar_cor_escrito_linha(self):
        color_text = self.Cor_linha.text()
        color = QtGui.QColor.fromString(color_text)
        if len(color_text) == 7 and color.isValid():

            if color.lightness() > 150:
                self.Cor_linha.setStyleSheet(
                    f"""color: #000000;background-color: {color_text}"""
                )
            else:
                self.Cor_linha.setStyleSheet(
                    f"""color: #ffffff;background-color: {color_text}"""
                )


    #procurar arquivo
    def arquivo_procurar(self):
        arquivos = QtWidgets.QFileDialog.getOpenFileNames(filter="Arquivo de dados (*.txt *.csv *.xlsx)")[0]
        if len(arquivos) >0:
            nomes = arquivos[0].split("/")[-1]
            for index in range(1,len(arquivos)):
                nomes = nomes + ", " + arquivos[index].split("/")[-1]
            self.Caminho_arquivo.setText(nomes)
            return arquivos
        
                    
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Castorplot"))
        self.Castorplot.setText(_translate("MainWindow", "Castorplot"))
        self.Importar_dados.setText(_translate("MainWindow", "Importar dados novos"))
        self.Sobre.setText(_translate("MainWindow", "Sobre"))
        self.Ajuda.setText(_translate("MainWindow", "Ajuda"))
        self.Arquivo_abrir.setText(_translate("MainWindow", "Abrir arquivo de analize"))
        self.continuar_import.setText(_translate("MainWindow", "Continuar"))
        self.voltar_import.setText(_translate("MainWindow", "Voltar"))
        self.label_11.setText(
            _translate("MainWindow", "Linhas do cabeçalho que deseja ignorar.")
        )
        self.label_10.setText(
            _translate(
                "MainWindow", "Escreva o delimitador da coluna. Para tab escreva TAB."
            )
        )
        self.label_12.setText(
            _translate("MainWindow", "Escreva o separador decimal dos dados.")
        )
        self.label_9.setText(
            _translate("MainWindow", "Importar arquivos para plotagem.")
        )
        self.procurar_arquivo.setText(_translate("MainWindow", "Abrir"))
        self.label_15.setText(_translate("MainWindow", "Plot dados puros"))
        self.continuar_dados_puros.setText(_translate("MainWindow", "Continuar"))
        self.voltar_dados_puros.setText(_translate("MainWindow", "Voltar"))
        self.label.setText(_translate("MainWindow", "FTIR, Raman e UvVis"))
        self.voltar_analise.setText(_translate("MainWindow", "Voltar"))
        self.check_nverter_eixo.setText(_translate("MainWindow", "Inverter eixo X"))
        self.label_17.setText(
            _translate("MainWindow", "Distancia entre linhas de dados.")
        )
        self.label_2.setText(
            _translate("MainWindow", "Escolha o intervalo para a análise dos dados.")
        )
        self.label_3.setText(_translate("MainWindow", "Valor mínimo X"))
        self.label_4.setText(_translate("MainWindow", "Valor máximo X"))
        self.label_44.setText(_translate("MainWindow", "Normalizar"))
        self.label_8.setText(
            _translate(
                "MainWindow", "Escolha o intervalo para a normalização dos dados."
            )
        )
        self.label_14.setText(_translate("MainWindow", "Valor mínimo X"))
        self.label_16.setText(_translate("MainWindow", "Valor máximo X"))
        self.check_normalizar_dados.setText(
            _translate("MainWindow", "Normalizar dados")
        )
        self.label_43.setText(_translate("MainWindow", "Tirar BaseLine"))
        self.Avancado.setText(_translate("MainWindow", "Avançado"))
        self.Modpoly.setText(_translate("MainWindow", "Modpoly "))
        self.ImodPloy.setText(_translate("MainWindow", "IModPoly "))
        self.Zhangfit.setText(_translate("MainWindow", "ZhangFit "))
        self.label_45.setText(_translate("MainWindow", "Parâmetros"))
        self.label_20.setText(_translate("MainWindow", "repitition"))
        self.label_19.setText(_translate("MainWindow", "porder"))
        self.label_18.setText(_translate("MainWindow", "lambda_"))
        self.checkBox.setText(_translate("MainWindow", "Remover Baseline"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Manipulação")
        )
        self.label_46.setText(_translate("MainWindow", "Título"))
        self.label_47.setText(_translate("MainWindow", "Eixo x"))
        self.label_48.setText(_translate("MainWindow", "Eixo y"))
        self.label_7.setText(_translate("MainWindow", "Cor do texto do gráfico"))
        self.label_24.setText(_translate("MainWindow", "Cor hexadecimal"))
        self.Cor_texto.setText(_translate("MainWindow", "#000000"))
        self.label_42.setText(_translate("MainWindow", "Cor da linha"))
        self.label_52.setText(_translate("MainWindow", "Cor hexadecimal"))
        self.label_5.setText(_translate("MainWindow", "Cor da borda do gráfico"))
        self.checkBox_2.setText(_translate("MainWindow", "Transparente"))
        self.label_22.setText(_translate("MainWindow", "Cor hexadecimal"))
        self.Cor_borda.setText(_translate("MainWindow", "#ffffff"))
        self.label_6.setText(_translate("MainWindow", "Cor do fundo do gráfico"))
        self.checkBox_3.setText(_translate("MainWindow", "Transparente"))
        self.label_23.setText(_translate("MainWindow", "Cor hexadecimal"))
        self.Cor_fundo.setText(_translate("MainWindow", "#ffffff"))
        self.label_26.setText(_translate("MainWindow", "Cor da grade do gráfico"))
        self.checkBox_6.setText(_translate("MainWindow", "Tirar grade"))
        self.label_27.setText(_translate("MainWindow", "Cor hexadecimal"))
        self.Cor_grade.setText(_translate("MainWindow", "#000000"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_9),
            _translate("MainWindow", "Estilo gráfico"),
        )
        self.Exportar_grafico.setText(_translate("MainWindow", "Exportar gráfico"))
        self.formato_png.setText(_translate("MainWindow", "PNG"))
        self.formato_pdf.setText(_translate("MainWindow", "PDF"))
        self.formato_svg.setText(_translate("MainWindow", "SVG"))
        self.Exportar_dados.setText(_translate("MainWindow", "Exportar dados"))
        self.CSV_export.setText(_translate("MainWindow", "CSV"))
        self.TXT_export.setText(_translate("MainWindow", "TXT"))
        self.Exportar_analise.setText(_translate("MainWindow", "Exportar análise"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Exportar")
        )
        self.label_36.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><a href="https://github.com/guidariani"><span style=" font-size:10pt; text-decoration: underline; color:#0000ff;">GitHub pessoal</span></a><span style=" font-size:10pt;"/></p></body></html>',
            )
        )
        self.label_34.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><a href="https://github.com/guilhermeilum"><span style=" font-size:10pt; text-decoration: underline; color:#0000ff;">GitHub acadêmico</span></a><span style=" font-size:10pt;"/></p></body></html>',
            )
        )
        self.voltar_sobre.setText(_translate("MainWindow", "Voltar"))
        self.Castorplot_2.setText(_translate("MainWindow", "Castorplot"))
        self.textBrowser.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Aplicativo:</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt;">É um aplicativo simples criado com python para manipulação de dados e plot dos mesmos, desenvolvido para facilitar para os alunos da Ilum Escola de Ciências a manipulação de dados dos equipamentos disponíveis na Ilum ou no CNPEM - Centro Nacional de Pesquisa em Energia e Materiais.</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt;">O nome não tem nenhum fato interessante, só não sabia que nome colocar e tirei de uma estrela.</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Desenvolvedor:</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt;">Eu sou Guilherme Gurian Dariani, aluno da Ilum, turma 2022, primeiramente peço desculpa pela interface gráfica não ser bonita, mas vou tentar arrumar depois, por enquanto tentarei deixar funcional, para os alunos da Ilum.</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt;">Esse é meu primeiro aplicativo, então provavelmente terá alguns problemas, qualquer bug me envie por e-mail.</span></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt;">Contato relacionado com o aplicativo será preferencialmente por e-mail, se for aluno da Ilum pode me procurar na faculdade que ajudo, para outros assuntos pode utilizar qualquer rede social.</span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;"><br /></p>\n'
                '<p align="justify" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Source Sans Pro,sans-serif\'; font-size:11pt; font-weight:600; color:#31333f; background-color:#f0f2f6;">Em nenhum caso o desenvolvedor será responsável por quaisquer erros, resultados ou informações incorretas.</span></p>\n'
                '<p align="justify" style="-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;"><br /></p></body></html>',
            )
        )
        self.label_28.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><a href="mailto:guidarianiapps@gmail.com"><span style=" font-size:10pt; text-decoration: underline; color:#0000ff;">guidarianiapps@gmail.com</span></a><span style=" font-size:10pt;"/></p></body></html>',
            )
        )
        self.label_37.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><a href="https://linktr.ee/guidariani"><span style=" font-family:\'Source Sans Pro,sans-serif\'; font-size:16px; text-decoration: underline; color:#0068c9; background-color:#f0f2f6;">Mais contatos</span></a></p></body></html>',
            )
        )
        self.menuarquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda"))
        self.actionImportar.setText(_translate("MainWindow", "Abrir"))
        self.actionImportar.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.action_novo.setText(_translate("MainWindow", "Novo"))
        self.action_novo.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionGitHub.setText(_translate("MainWindow", "GitHub"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
